spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: userdemo #服务名以及注册时的id

mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml

server:
  port: 8762
#  port: ${random.int[10000,19999]} #随机端口号
  servlet:
    context-path: /
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #该地址和默认地址一样
    healthcheck:
      enabled: true #将健康监测交给actuator的/health端点
  instance:
    instance-id: ${spring.application.name}:${random.int} #设置实例id
management:
  endpoints:
    web:
      exposure:
        include: "*"  #beans,health
  endpoint:
    health:
      show-details: always
    shutdown: #post请求
      enabled: true

---
spring:
  profiles: test

  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: userdemo

mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
  instance:
    prefer-ip-address: true #允许使用ip访问注册中心
