eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/

server:
  port: 8760

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DiamondCrevasseDC/SpringCloud.git
          search-paths: "{application}"
          default-label: master

  application:
    name: config-server
